package msg_status

import (
	"fmt"
	"time"

	"github.com/moov-io/rtp20022/pkg/tch"
)

// MessageID returns a Message Identification for pacs.002 messages
//
// Format: MYYYYMMDDbbbbbbbbbbbBAAAnnnnnnnnnnn
// Pos. 01-01 - Prefix ‘M’
// Pos. 02-09 - File creation date in format YYYYMMDD
// Pos. 10-20 - Participant ID (11 characters)
// Pos. 21-21 - Message generation source (“B” if generated by a Participant; 'H' if generated by RTP)
// Pos. 22-24 - Discretionary bank field (3 digit alpha numeric that can be used to serialize, identify specific systems, etc.)
// Pos. 25-35 - Message serial number (11 numeric characters)
//
// Example: M2017111202001000101BMSR00000000002
func MessageID(ts time.Time, participantID string, serial string) string {
	creationDate := ts.Format("20060102")
	messageSerial := tch.NumericSerialNumber(11)

	return fmt.Sprintf("M%s%11.11sB%3.3s%s", creationDate, participantID, serial, messageSerial)
}
