package credit_transfer

import (
	"fmt"
	"time"

	"github.com/moov-io/rtp20022/pkg/tch"
)

// MessageID returns a Message Identification for pacs.008 messages
//
// Format: MYYYYMMDDbbbbbbbbbbbBAAAnnnnnnnnnnn
// Pos. 01-01 - Prefix "M"
// Pos. 02-09 - File creation date in format YYYYMMDD
// Pos. 10-20 - FI Identifier (11 digit Participant ID)
// Pos. 21-21 - Message generation source ("B" if generated by a TCH FI)
// Pos. 22-24 - Alphabetic serial identifier (3 alphabetic characters)
// Pos. 25-35 - Message serial number (11 numeric characters)
//
// Example: M2015111511021200201BFFF00000000001
func MessageID(ts time.Time, participantID string, serial string) string {
	creationDate := ts.Format("20060102")
	messageSerial := tch.NumericSerialNumber(11)

	return fmt.Sprintf("M%s%11.11sB%3.3s%s", creationDate, participantID, serial, messageSerial)
}
