package rtp

import (
	"fmt"
	"time"
)

// CaseAssignmentID generates an Assignment Identifier for a Case.
// This is used in camt.029 responses.
//
// Format: MYYYYMMDDbbbbbbbbbbbBAAAnnnnnnnnnnn
// Pos. 01-01 – Prefix ‘M’
// Pos. 02-09 - File creation date in format YYYYMMDD
// Pos. 10-20 - Participant ID (11 characters)
// Pos. 21-21 - Message generation source ("B" if generated by a Participant)
// Pos. 22-24 - Discretionary bank field (3 digit alpha numeric that can be used to serialize, identify specific systems, etc.)
// Pos. 25-35 - Message serial number (11 numeric characters)
func CaseAssignmentID(ts time.Time, participantID, bankField string, serialFunc SerialGenerator) string {
	timestamp := ts.Format("20060102")
	partID := fmt.Sprintf("%011.11s", participantID)
	bank := fmt.Sprintf("%03.3s", bankField)
	serial := pickGenerator(serialFunc, NumericSerialNumber)(11)

	return fmt.Sprintf("M%s%sB%s%011.11s", timestamp, partID, bank, serial)
}
