package rtp

import (
	"fmt"
	"time"
)

// InstructionID generates a Instruction Identification value.
//
// Format: YYYYMMDDbbbbbbbbbbbBAAAAnnnnnnnnnnn
// Pos. 01-08 - File creation date in format YYYYMMDD
// Pos. 09-19 - Participant ID (11 characters)
// Pos. 20-20 - Message generation source (“B” if generated by a Participant)
// Pos. 21-24 - Discretionary bank field (4 digit alpha numeric that can be used to serialize, identify specific systems, etc.)
// Pos. 25-35 - Message serial number (11 numeric characters)
//
// Example: 2016021812345678901BD61U00000000006
func InstructionID(ts time.Time, participantID, bankField string) string {
	timestamp := ts.Format("20060102")
	partID := fmt.Sprintf("%011.11s", participantID)
	bank := fmt.Sprintf("%4.4s", bankField)
	serial := NumericSerialNumber(11)

	return fmt.Sprintf("%s%sB%s%011.11s", timestamp, partID, bank, serial)
}
