package rtp

import (
	"fmt"
	"time"
)

// MessageID returns a Message Identification for pacs.008 messages
//
// Format: MYYYYMMDDbbbbbbbbbbbBAAAnnnnnnnnnnn
// Pos. 01-01 - Prefix "M"
// Pos. 02-09 - File creation date in format YYYYMMDD
// Pos. 10-20 - FI Identifier (11 digit Participant ID)
// Pos. 21-21 - Message generation source ("B" if generated by a TCH FI)
// Pos. 22-24 - Alphabetic serial identifier (3 alphabetic characters)
// Pos. 25-35 - Message serial number (11 numeric characters)
//
// Example: M2015111511021200201BFFF00000000001
func MessageID(ts time.Time, participantID string, serial string, messageSerialFunc SerialGenerator) string {
	creationDate := ts.Format("20060102")
	messageSerial := pickGenerator(messageSerialFunc, NumericSerialNumber)(11)

	return fmt.Sprintf("M%s%11.11sB%3.3s%s", creationDate, participantID, serial, messageSerial)
}

// AdmnMessageID generates a Message Identification value.
//
// Format: YYYYMMDDHHMMSSbbbbbbbbbbbXXXXXXXXXX
// Pos. 01-14 - File creation date in format YYYYMMDDHHMMSS
// Pos. 15-25 - 11 character Participant Identifier for FIs and TPSP
// Pos. 26-35 - Participant specific Message serial number (up to 10 characters)
//
// Example: 2016021810064302120020101B61NHTCSG6
func AdmnMessageID(ts time.Time, participantID string, serialFunc SerialGenerator) string {
	timestamp := ts.Format("20060102150405")
	partID := fmt.Sprintf("%011.11s", participantID)
	serial := pickGenerator(serialFunc, AlphaSerialNumber)(10)

	return fmt.Sprintf("%s%s%010.10s", timestamp, partID, serial)
}
